name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Update the branch name to 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2  # Correct action for Pages artifact upload

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
